apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextra-v3-test-service
  labels:
    app: nextra-v3-test-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextra-v3-test-service
  template:
    metadata:
      labels:
        app: nextra-v3-test-service
    spec:
      containers:
      - name: nextra-v3-test-service
        image: nextra-v3-test-service
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextra-v3-test-service
spec:
  selector:
    app: nextra-v3-test-service
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP