name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Update dependencies
        run: pnpm update
      
      - name: Run Codependence update
        run: pnpm codependence update
      
      - name: Run tests
        run: pnpm test
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): update dependencies'
          body: |
            This PR updates project dependencies to their latest versions.
            
            - Automated using Codependence
            - All tests are passing
          branch: update-dependencies
          base: main
          labels: dependencies